name: real_world
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  firebase_analytics: ^5.0.2
  firebase_core: ^0.4.0+9
  cloud_firestore: 
  firebase_storage:
  image_picker:
  cached_network_image: ^2.0.0
  shared_preferences: ^0.5.3+5
  flutter_image_compress:
  path_provider:
  uuid:
  provider: 
  image_cropper:
  intl:
  firebase_database:
  shimmer:
  font_awesome_flutter:
  animator: 
  google_fonts: ^0.3.5
  fl_chart:
  percent_indicator:
  dotted_border:
  path_drawing:
  google_sign_in: ^3.2.4
  auto_size_text: ^2.1.0
  bottom_navy_bar: ^3.0.0  
  fluttertoast:  
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^0.8.4
  photo_view: ^0.5.0
  
   


dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true

 
  assets:
   - assets/images/
   - images/img_not_available.jpeg
   - images/mimi1.gif
   - images/mimi2.gif
   - images/mimi3.gif
   - images/mimi4.gif
   - images/mimi5.gif
   - images/mimi6.gif
   - images/mimi7.gif
   - images/mimi8.gif
   - images/mimi9.gif

 
  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: UbuntuMono
      fonts:
        - asset: assets/fonts/UbuntuMono-Regular.ttf
 